### ISSUE TITLE
Dummy question

### ISSUE THREAD

**Issue by awi69** [SentiQ/ioBroker.hydrawise#16]
sorry ... ich stelle mich möglicherweise nicht besonders schlau an ... aber ich wollte den hydrawise adapter in Iobroker einbinden und habe ihn mittels nmp -i .... installiert. Ich sehen aber keinen hydrawise adapter in der Iobroker oberfläche. Ich habe sicher einen "Denkfehler" oder ?  Danke schon mal

**Comment by SentiQ** [comment]
Der Adapter kann ganz normal über die iobroker-Oberfläche aus dem Beta-Repository installiert werden.

**Comment by awi69** [comment]
OH, Danke !!! das war dann einfach :). Eine Frage noch: Ich habe den Adapter hauptsächlich installiert, weil ich gern mehr als eine Zone/Ventil gleichzeitig benutzen/betätigen würde. In der App ist das so meines Wissens nicht vorgesehen. Geht das überhaupt ?

**Comment by SentiQ** [comment]
Das lässt der Controller nicht zu. Der schaltet immer nur maximal ein Ventil.

**Comment by awi69** [comment]
ich dachte es mir fast, habe zum probieren mal an den unterschiedlichsten stellen werte geschrieben, die alle für sich toll funktionieren aber eben nix simultan … trotzdem ein toller adapter Danke dafür … mal sehen was mir da nicht noch für Ideen kommen
