### ISSUE TITLE
Enhancement - Datenpunkt für das Starten eines Kreises mit der Default-Laufzeit

### ISSUE THREAD

**Issue by aDabbelju** [SentiQ/ioBroker.hydrawise#17]
Erst einmal Danke für deine Mühe und Zeit.
Einen Vorschlag zur Verbesserung hätte ich jedoch, da die API dahingehend etwas starr ist. Letztendlich besitzt jede Zone eine konfigurierte Zeit (Datenpunkt "run" in s) für die Sprengung eines Kreises. Wenn ich jedoch einen Kreis mit der bereits konfigurierten Zeit starten möchte, muss man sich ein Script/Blockly basteln. Dies liest die Zeit ("run") in Sekunden aus und setzt diese in den Datenpunkt "runZone". Hier wünschte ich mir eine elegantere Lösung, beispielsweise einen extra Datenpunkt (Switch), der den Kreis direkt starten und stoppen kann.

switch to "true" -> starte Kreis mit X Sekunden (X=Wert aus "run") -> danach Wechsel auf false
switch to "false" -> stoppe den Kreis

Damit ließe sich der Adapter direkt in eine Visualisierung einbinden. Hoffentlich ist mein Vorschlag verständlich 🙂

Grüße

**Comment by SentiQ** [comment]
Als Switch "runDefault" umgesetzt
