### ISSUE TITLE
Regensensor Hunter Rain-Clik wird nicht ausgelesen

### ISSUE THREAD

**Issue by mbhomie007** [SentiQ/ioBroker.hydrawise#18]
v0.1.2

Regensensor wird nicht korrekt ausgelesen.

Ich denke der Regensensor müsste ein "Ausgelöst/1" oder "nicht ausgelöst/0" bei "Input" anzeigen.

![image](https://github.com/SentiQ/ioBroker.hydrawise/assets/64688879/40aa5a89-9d79-451d-8edc-6033d0d302af)

**Comment by mbhomie007** [comment]
Mein Regensensor ist im Moment "Ausgelöst", lässt eine Bewässerung also nicht zu.

Der Status wird aber wie gesagt leider nicht ausgelesen.

![Screenshot_20230828_121028_Hydrawise.jpg](https://github.com/SentiQ/ioBroker.hydrawise/assets/64688879/c61b232d-3afb-47cf-a68d-1feefeb1148d)

**Comment by SentiQ** [comment]
@mbhomie007 wie vermutet, die API liefert hier in jedem Zustand eine 1. Das gleiche Problem habe ich auch beim Durchflussmesser, da ändern sich die Werte auch nie.

**Comment by mbhomie007** [comment]
Also liefert die API diesen Datenpunkt also nicht? 

Wie bekomme ich denn die andere API, dort soll der Sensor Status abrufbar sein? 

![Screenshot_20230828_151558_Chrome.jpg](https://github.com/SentiQ/ioBroker.hydrawise/assets/64688879/33f12b3b-4f94-4a56-ade7-31e0b5a8d692)

**Comment by SentiQ** [comment]
Ich hatte dem Anthony Long schon mal geschrieben und er meinte die GraphQL API ist derzeit nur für kommerzielle Zwecke verfügbar.

**Comment by mbhomie007** [comment]
Okay, schade.
Trotzdem danke für deine Rückmeldung.
