### ISSUE TITLE
Adapter stürzt ab - Mehrere Fehler im Log

### ISSUE THREAD

**Issue by mbhomie007** [SentiQ/ioBroker.hydrawise#24]
<html>
<body>

hydrawise.0 | 2023-09-03 12:39:21.516 | info | starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.hydrawise, node: v18.17.1, js-controller: 5.0.12
-- | -- | -- | --
host.raspberrypi | 2023-09-03 12:39:18.751 | info | instance system.adapter.hydrawise.0 started with pid 16738
host.raspberrypi | 2023-09-03 12:38:48.494 | info | Restart adapter system.adapter.hydrawise.0 because enabled
host.raspberrypi | 2023-09-03 12:38:48.493 | error | instance system.adapter.hydrawise.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
hydrawise.0 | 2023-09-03 12:38:48.369 | error | DB closed
hydrawise.0 | 2023-09-03 12:38:48.369 | error | Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at ObjectsInRedisClient._getObject (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:2416:37) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:2463:33) at process.processImmediate (node:internal/timers:478:21)
hydrawise.0 | 2023-09-03 12:38:48.367 | error | unhandled promise rejection: DB closed
hydrawise.0 | 2023-09-03 12:38:48.367 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hydrawise.0 | 2023-09-03 12:38:48.363 | error | Connection is closed.
hydrawise.0 | 2023-09-03 12:38:48.362 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:629:26) at Socket.emit (node:events:514:28) at TCP.<anonymous> (node:net:323:12)
hydrawise.0 | 2023-09-03 12:38:48.361 | error | unhandled promise rejection: Connection is closed.
hydrawise.0 | 2023-09-03 12:38:48.361 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hydrawise.0 | 2023-09-03 12:38:48.349 | info | terminating
hydrawise.0 | 2023-09-03 12:38:48.333 | info | State value to set for "hydrawise.0.customer.51" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.322 | info | State value to set for "hydrawise.0.customer.50" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.318 | info | State value to set for "hydrawise.0.customer.49" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.300 | info | State value to set for "hydrawise.0.customer.48" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.284 | info | State value to set for "hydrawise.0.customer.47" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.236 | info | State value to set for "hydrawise.0.customer.46" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.226 | info | State value to set for "hydrawise.0.customer.45" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.218 | info | State value to set for "hydrawise.0.customer.44" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.161 | info | State value to set for "hydrawise.0.customer.43" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.147 | info | State value to set for "hydrawise.0.customer.42" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.092 | info | State value to set for "hydrawise.0.customer.41" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.082 | info | State value to set for "hydrawise.0.customer.40" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.072 | info | State value to set for "hydrawise.0.customer.39" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.063 | info | State value to set for "hydrawise.0.customer.38" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.053 | info | State value to set for "hydrawise.0.customer.37" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:48.044 | info | State value to set for "hydrawise.0.customer.36" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.997 | info | State value to set for "hydrawise.0.customer.35" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.988 | info | State value to set for "hydrawise.0.customer.34" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.979 | info | State value to set for "hydrawise.0.customer.33" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.969 | info | State value to set for "hydrawise.0.customer.32" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.959 | info | State value to set for "hydrawise.0.customer.31" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.949 | info | State value to set for "hydrawise.0.customer.30" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.938 | info | State value to set for "hydrawise.0.customer.29" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.928 | info | State value to set for "hydrawise.0.customer.28" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.918 | info | State value to set for "hydrawise.0.customer.27" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.863 | info | State value to set for "hydrawise.0.schedule.57" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.851 | info | State value to set for "hydrawise.0.customer.26" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.847 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hydrawise.0 | 2023-09-03 12:38:47.846 | info | terminating
hydrawise.0 | 2023-09-03 12:38:47.839 | error | content.relays is not iterable
hydrawise.0 | 2023-09-03 12:38:47.839 | error | TypeError: content.relays is not iterable at /opt/iobroker/node_modules/iobroker.hydrawise/build/main.js:161:39
hydrawise.0 | 2023-09-03 12:38:47.837 | error | unhandled promise rejection: content.relays is not iterable
hydrawise.0 | 2023-09-03 12:38:47.836 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hydrawise.0 | 2023-09-03 12:38:47.828 | info | State value to set for "hydrawise.0.schedule.56" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.817 | info | State value to set for "hydrawise.0.customer.25" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.805 | info | State value to set for "hydrawise.0.schedule.55" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.797 | info | State value to set for "hydrawise.0.customer.24" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.743 | info | State value to set for "hydrawise.0.schedule.54" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.727 | info | State value to set for "hydrawise.0.customer.23" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.725 | info | State value to set for "hydrawise.0.schedule.53" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.712 | info | State value to set for "hydrawise.0.customer.22" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.698 | info | State value to set for "hydrawise.0.schedule.52" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.640 | info | State value to set for "hydrawise.0.customer.21" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.637 | info | State value to set for "hydrawise.0.schedule.51" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.625 | info | State value to set for "hydrawise.0.customer.20" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.617 | info | State value to set for "hydrawise.0.schedule.50" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.603 | info | State value to set for "hydrawise.0.customer.19" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.602 | info | State value to set for "hydrawise.0.schedule.49" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.588 | info | State value to set for "hydrawise.0.customer.18" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.581 | info | State value to set for "hydrawise.0.schedule.48" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.523 | info | State value to set for "hydrawise.0.customer.17" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.520 | info | State value to set for "hydrawise.0.schedule.47" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.515 | info | State value to set for "hydrawise.0.customer.16" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.511 | info | State value to set for "hydrawise.0.schedule.46" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.494 | info | State value to set for "hydrawise.0.customer.15" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.487 | info | State value to set for "hydrawise.0.schedule.45" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.434 | info | State value to set for "hydrawise.0.customer.14" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.423 | info | State value to set for "hydrawise.0.schedule.44" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.419 | info | State value to set for "hydrawise.0.customer.13" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.402 | info | State value to set for "hydrawise.0.schedule.43" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.393 | info | State value to set for "hydrawise.0.customer.12" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.381 | info | State value to set for "hydrawise.0.schedule.42" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.379 | info | State value to set for "hydrawise.0.customer.11" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.362 | info | State value to set for "hydrawise.0.schedule.41" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.350 | info | State value to set for "hydrawise.0.customer.10" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.349 | info | State value to set for "hydrawise.0.schedule.40" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.336 | info | State value to set for "hydrawise.0.customer.9" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.327 | info | State value to set for "hydrawise.0.schedule.39" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.318 | info | State value to set for "hydrawise.0.customer.8" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.276 | info | State value to set for "hydrawise.0.schedule.38" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.275 | info | State value to set for "hydrawise.0.customer.7" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.270 | info | State value to set for "hydrawise.0.schedule.37" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.250 | info | State value to set for "hydrawise.0.customer.6" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.241 | info | State value to set for "hydrawise.0.schedule.36" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.230 | info | State value to set for "hydrawise.0.customer.5" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.226 | info | State value to set for "hydrawise.0.schedule.35" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.178 | info | State value to set for "hydrawise.0.customer.4" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.106 | info | State value to set for "hydrawise.0.schedule.34" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.094 | info | State value to set for "hydrawise.0.customer.3" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.092 | info | State value to set for "hydrawise.0.schedule.33" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.079 | info | State value to set for "hydrawise.0.customer.2" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.072 | info | State value to set for "hydrawise.0.schedule.32" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.063 | info | State value to set for "hydrawise.0.customer.1" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.053 | info | State value to set for "hydrawise.0.schedule.31" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.044 | info | State value to set for "hydrawise.0.customer.0" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:47.029 | info | State value to set for "hydrawise.0.schedule.30" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.944 | info | State value to set for "hydrawise.0.schedule.29" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.934 | info | State value to set for "hydrawise.0.schedule.28" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.923 | info | State value to set for "hydrawise.0.schedule.27" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.911 | info | State value to set for "hydrawise.0.schedule.26" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.848 | info | State value to set for "hydrawise.0.schedule.25" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.815 | info | State value to set for "hydrawise.0.schedule.24" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.801 | info | State value to set for "hydrawise.0.schedule.23" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.754 | info | State value to set for "hydrawise.0.schedule.22" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.744 | info | State value to set for "hydrawise.0.schedule.21" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.731 | info | State value to set for "hydrawise.0.schedule.20" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.720 | info | State value to set for "hydrawise.0.schedule.19" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.665 | info | State value to set for "hydrawise.0.schedule.18" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.650 | info | State value to set for "hydrawise.0.schedule.17" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.639 | info | State value to set for "hydrawise.0.schedule.16" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.585 | info | State value to set for "hydrawise.0.schedule.15" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.575 | info | State value to set for "hydrawise.0.schedule.14" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.566 | info | State value to set for "hydrawise.0.schedule.13" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.550 | info | State value to set for "hydrawise.0.schedule.12" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.535 | info | State value to set for "hydrawise.0.schedule.11" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.487 | info | State value to set for "hydrawise.0.schedule.10" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.478 | info | State value to set for "hydrawise.0.schedule.9" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.466 | info | State value to set for "hydrawise.0.schedule.8" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.456 | info | State value to set for "hydrawise.0.schedule.7" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.447 | info | State value to set for "hydrawise.0.schedule.6" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.435 | info | State value to set for "hydrawise.0.schedule.5" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.386 | info | State value to set for "hydrawise.0.schedule.4" has to be type "number" but received type "string"
hydrawise.0 | 2023-09-03 12:38:46.370 | warn | Object of state "hydrawise.0.schedule.3" is missing the required property "common.type"
hydrawise.0 | 2023-09-03 12:38:46.354 | warn | Object of state "hydrawise.0.schedule.2" is missing the required property "common.type"
hydrawise.0 | 2023-09-03 12:38:46.349 | warn | Object of state "hydrawise.0.schedule.1" is missing the required property "common.type"
hydrawise.0 | 2023-09-03 12:38:46.308 | info | State value to set for "hydrawise.0.schedule.0" has to be type "number" but received type "string"

</body>
</html>

**Comment by SentiQ** [comment]
How can I reproduce that? I have no errors or warnings with the newest version since days.

**Comment by mbhomie007** [comment]
No idea... Many days the adapter works fine. Today a look in the log and found many errors. I will look at them in future.
