### ISSUE TITLE
Will there be an official version for iobroker?

### ISSUE THREAD

**Issue by guitardoc** [SentiQ/ioBroker.hydrawise#66]
I was just wondering if you could already say if and when there will be an official version of this adapter? I am very interested in it. Thank you very much.

**Comment by SentiQ** [comment]
Hi, thanks for asking.
Official version is on the way.

**Comment by guitardoc** [comment]
Thank you very much for the reply. Looking forward to it very much!!! Am 08.04.2024 um 20:40 schrieb Yves Nüßer ***@***.***>:﻿
Hi, thanks for asking.
Official version is on the way.

**Comment by SentiQ** [comment]
Official version 0.2.8 is in stable now.
