### ISSUE TITLE
No bug - just a question

### ISSUE THREAD

**Issue by guitardoc** [SentiQ/ioBroker.hydrawise#69]
Hallo Yves,

Danke für die Bereitstellung des Adapters! Ich habe nur eine kurze Frage - in welchen Zeitabständen werden die Daten gezogen? Ich habe irgendwo eine 60 gefunden - sind das Sekunden?
Ich hatte bisher die API direkt per http abgefragt und das in Abständen von 60 Sekunden. Hab darüber berechnet, wann die Brunnenpumpe angeworfen werden muss. Ich würde natürlich gern auf deinen Adapter umsteigen und muss dann nur schauen, wie die Parameter zusammen passen.

Danke schon mal vorab für die Info!

**Comment by SentiQ** [comment]
Guter Hinweis, ich hatte das mal zu Testzwecken hoch gesetzt auf 5 Minuten für die beiden Endpunkte.
Werde das anpassen bzw. am besten gleich konfigurierbar machen.

**Comment by SentiQ** [comment]
Die Anpassung ist jetzt auf Github und npm verfügbar, sollte bald auch im Beta-Repo verfügbar sein.
Sobald es im Stable ist, gebe ich Bescheid, das wird aber ein paar Tage dauern.

**Comment by guitardoc** [comment]
Hab die neue Version gerade installiert - vielen Dank für die Konfigurierbarkeit der Polltime! Funktioniert einwandfrei!

Ich habe noch eine andere Frage - hast du herausbekommen, was der Eintrag unter schedule.zone.type beinhaltet und was die einzelnen Nummern bedeuten? Wenn ich nicht völlig blind bin, dann steht in der API-Doku nichts zu diesem Wert drin und ich habe mich schon immer gefragt, was in diesem Punkt gespeichert wird. Bei mir gibt es im Moment die Werte 6, 9 und 110. Hast du eine Idee, was die bedeuten?

**Comment by guitardoc** [comment]
Noch eine Info: Ich bekomme immer mal wieder diese Fehlermeldung:
`hydrawise.0
2024-04-21 15:06:22.808	warn	received 429 response from /api/v1/customerdetails.php with content: "Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint."

hydrawise.0
2024-04-21 15:01:22.042	warn	received 429 response from /api/v1/customerdetails.php with content: "Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint."

hydrawise.0
2024-04-21 14:56:21.226	warn	received 429 response from /api/v1/customerdetails.php with content: "Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint."
`
Polltime ist auf 60 Sekunden eingestellt.

**Comment by SentiQ** [comment]
> Ich habe noch eine andere Frage - hast du herausbekommen, was der Eintrag unter schedule.zone.type beinhaltet und was die einzelnen Nummern bedeuten? Wenn ich nicht völlig blind bin, dann steht in der API-Doku nichts zu diesem Wert drin und ich habe mich schon immer gefragt, was in diesem Punkt gespeichert wird. Bei mir gibt es im Moment die Werte 6, 9 und 110. Hast du eine Idee, was die bedeuten?

Leider kann ich dir das nicht beantworten - habe überall eine 110.

**Comment by SentiQ** [comment]
> Noch eine Info: Ich bekomme immer mal wieder diese Fehlermeldung: `hydrawise.0 2024-04-21 15:06:22.808 warn received 429 response from /api/v1/customerdetails.php with content: "Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint."

Der Endpunkt wird nur alle 5 Minuten abgefragt, die konfigurierbare Polltime bezieht sich nur auf den Schedule-Endpunkt.
Habe die Meldung nur, wenn ich bei der Entwicklung den Adapter mehrfach neu starte. Bekommst du sie auch, wenn er ganz normal läuft ohne dass du ihn neu gestartet hast?

**Comment by guitardoc** [comment]
Du hast recht - die Meldung kommt auch bei mir nur, wenn der Adapter neu gestartet wurde. Danach läuft er sauber durch. Also alles schick - vielen Dank noch mal für deine Arbeit!
